config/routes.rb
Rails.application.routes.draw do

  get 'pendingcommands/index'

  get 'pendingcommands/create'

  resources :device_dashboard, only:  [:index, :show]
  resources :devices do
    resources :pendingcommands, only: [:index, :create], :defaults => {:format => :json}
    resources :uploaded_files, only: [:index, :show, :destroy]
  end

  if Settings.registration.invite_only
    devise_for :users, :controllers => { :registrations => "registration_disabled" }
  else
    devise_for :users
  end

  ActiveAdmin.routes(self)

  get 'main_page/index'
  root 'main_page#index'

  #get 'locationhistory' => 'location_history#index'

  resources :location_history, only:  [:index, :show]

  namespace :api, :defaults => {:format => :json}, :constraints => {:format => /(xml|json)/} do
    namespace :v1 do
      resource :device, path: ":device_key", only: [:update, :show] do
        resources :locations, only: [:create]
        resources :pendingcommands, only: [:index, :update]
        resources :messages, only: [:create]
        resources :uploaded_files, only: [:create]
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/device.rb
class Device < ActiveRecord::Base
  before_create :generate_key
  belongs_to :user
  has_many :locations, :dependent => :destroy
  has_many :pendingcommands, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :uploaded_files, :dependent => :destroy

  validates_presence_of :name

  def to_json
    Jbuilder.encode do |json|
      json.base_url Settings.host_config.base_url
      json.base_url_port Settings.host_config.ssl_port
      json.device_key self.key
    end
  end

private

  def generate_key
    begin
      self.key = SecureRandom.hex(32)
    end while self.class.exists?(key: key)
  end
end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < Api::V1::BaseController

  def show
  end

  def update
    if @device.update(allowed_params)
      head :ok
    else
      render json: @device.errors, status: :unprocessable_entity
    end
  end

  private

  def allowed_params
    params.require(:device).permit(:gcm_regid)
  end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = current_user.devices
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
		qr_size = 5
		qr_size_pixels = Settings.view_config.qrcode_size.to_i
		@qrcode = nil
		while @qrcode == nil && qr_size < 20
		  begin
		    @qrcode = RQRCode::QRCode.new(@device.to_json, :size => qr_size, :level => :h ).to_img.resize(qr_size_pixels, qr_size_pixels).to_data_url
		  rescue RQRCode::QRCodeRunTimeError => e
		    qr_size += 1
		  end
    end
    @default_cert = Certificate.default_certificate
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.user = current_user
    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = current_user.devices.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name)
    end
end

app/helpers/api/v1/devices_helper.rb
module Api::V1::DevicesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for @device, :html => { :class => 'form-horizontal' } do |f| %>
  
	<% if @device.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
		</div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                devices_path, :class => 'btn' %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.name, device_path(device) %></td>
        <td><%=l device.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      device_path(device),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/show.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @device.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong>Saved locations:</strong></dt>
  <dd><%= @device.locations.size %></dd>
  <dt><strong><%= link_to "Uploaded Files", device_uploaded_files_path(@device) %></strong></dt>
  <dd><%= @device.uploaded_files.size %></dd>
  <dt><strong>Last locations:</strong></dt>
  <% @device.locations.last(3).reverse.each do |location| %>
    <dd><%= location %></dd>
  <% end %>
  <dt><strong>Config:</strong></dt>
  <% unless @qrcode.nil? %>
  	<dd><%= image_tag @qrcode %></dd>
  	<dd>Scan this qrcode when setting up your device</dd>
  <% end %>
    <dt><strong>Confirmation Hash:</strong></dt>
    <% if @default_cert %>
      <dd><%= @default_cert.cert_hash %></dd>
      <dd>Please confirm that this hash matches the one shown on your mobile device</dd>
    <% else %>
      <dd>Default certificate not yet configured, please contact the site admin.</dd>
    <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              devices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_device_path(@device), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              device_path(@device),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>