config/routes.rb
Rails.application.routes.draw do

  get 'pendingcommands/index'

  get 'pendingcommands/create'

  resources :device_dashboard, only:  [:index, :show]
  resources :devices do
    resources :pendingcommands, only: [:index, :create], :defaults => {:format => :json}
    resources :uploaded_files, only: [:index, :show, :destroy]
  end

  if Settings.registration.invite_only
    devise_for :users, :controllers => { :registrations => "registration_disabled" }
  else
    devise_for :users
  end

  ActiveAdmin.routes(self)

  get 'main_page/index'
  root 'main_page#index'

  #get 'locationhistory' => 'location_history#index'

  resources :location_history, only:  [:index, :show]

  namespace :api, :defaults => {:format => :json}, :constraints => {:format => /(xml|json)/} do
    namespace :v1 do
      resource :device, path: ":device_key", only: [:update, :show] do
        resources :locations, only: [:create]
        resources :pendingcommands, only: [:index, :update]
        resources :messages, only: [:create]
        resources :uploaded_files, only: [:create]
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ThreeHeadedMonkeyWeb" %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :head %>
  </head>
  <body>

    <%= nav_bar :fixed => :top, :brand => "ThreeHeadedMonkey", :responsive => true do %>
      <%= menu_group do %>
        <% if user_signed_in? %>
          <%= drop_down "Devices" do %>
            <%= menu_item "Manage your Devices", devices_path %>
            <%= menu_item "Location History", location_history_index_path %>
            <%= menu_item "Dashboard", device_dashboard_index_path %>
          <% end %>
        <% end %>
        <%= menu_item "About Us" %>
        <%= menu_item "Contact" %>
      <% end %>
      <%= menu_group :pull => :right do %>
        <% if user_signed_in? %>
          <%= drop_down current_user.email do %>
            <%= menu_item "Account", edit_user_registration_path %>
            <% if current_user.invitation_limit && current_user.invitation_limit > 0 %>
              <%= menu_item "Invite a friend", new_user_invitation_path %>
            <% end %>
            <%= menu_item 'Sign out', destroy_user_session_path, :method=>'delete' %>
          <% end %>
        <% else %>
          <%= menu_item 'Sign in', new_user_session_path %>
          <% unless Settings.registration.invite_only %>
            <%= menu_item 'Sign up', new_user_registration_path %>
          <% end %>
        <% end %>
      <% end %>


    <% end %>

    <div class="container" id="main_content">
        <%= bootstrap_flash(options = {}) %>
        <%= yield %>
    </div>


  </body>
</html>